### ISSUE TITLE
Suppression list search should support paging/cursors

### ISSUE THREAD

**Issue by ewandennis** [SparkPost/sparkpost-cli#15]
To support extraction of a user's whole suppression list, it'd be ideal if the CLI used the `cursor` URI parameter to retrieve all suppression list search results rather than the default 1k.

**Comment by yepher** [comment]
I'll look into this and get back to you on it. I thought we already supported this.

**Comment by yepher** [comment]
Ok, I refreshed my memory on that. I will add `cursor` functionality.

**Comment by yepher** [comment]
Search [API](https://developers.sparkpost.com/api/suppression-list.html#suppression-list-search-get)

I had a quick look at SparkPost Go library and did immediately see cursor support. Will investigate more.

**Comment by yepher** [comment]
Testing search/cursor with > 1M entries in Suppression list and it is works:

```
./sp-suppression-list-cli --command search |wc -l
 1112581

```

**Comment by yepher** [comment]
This feature has been released.
