### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by maxcodes** [SparkPost/sparkpost-cli#19]
I've spent about 20min trying to find how to install the cli...it would be helpful to add that to the Readme :)

**Comment by yepher** [comment]
Noted! I will add more details about how to:

* Retrieve the latest `sparkpost_cli.zip` from [here](https://github.com/SparkPost/sparkpost-cli/releases)
* Unzip
* Set up your [environment](https://github.com/SparkPost/sparkpost-cli#environment) (or pass on command line)
* run the binary for your platform

**Comment by yepher** [comment]
Fixed in commit 14af441
